### ISSUE TITLE
not found in xfce "Window Manager"

### ISSUE THREAD

**Issue by seahime** [sixsixfive/DarK#2]
I installed DarK theme following the "README.md--Installation--Manual", and I can active it in xfce's setting tool "Appearance", but can't find it in  "Window Manager".
My distribution is Fedora 27 with xfce

**Comment by sixsixfive** [comment]
the WM themes are in the Extras folder(https://github.com/sixsixfive/DarK/tree/master/Extras/Sub_themes) just copy the wanted one to the themes folder
